SHELL := /bin/bash

ONE_VERSION     ?= 6.10
SSH_PUB_KEY     ?= $(shell cat ~/.ssh/id_*.pub)
ONE_DEPLOY      ?= ansible/one-deploy

ONE_PASSWORD    ?= $(shell if [ -z "$$ONE_PASSWORD" ]; then openssl rand -hex 8; else echo "$$ONE_PASSWORD"; fi)

# Networking
BRIDGE          ?= brpub
NET             ?= 172.20.0
NET_ADDR        ?= ${NET}.0
NET_GW          ?= ${NET}.1
NET_MASK        ?= 255.255.255.0
NET_CIDR        ?= 24
NET_IP1         ?= ${NET}.3
PUBLIC_NIC      ?= eth0


define ONE_DEPLOY_INVENTORY =
---
all:
  vars:
    ansible_user: root
    one_version: '${ONE_VERSION}'
    one_pass: '${ONE_PASSWORD}'
    unattend_disable: true
    vn:
      service:
        managed: true
        template:
          VN_MAD: dummy
          BRIDGE: ${BRIDGE}
          BRIDGE_TYPE: linux
          AR:
            TYPE: IP4
            IP: ${NET_IP1}
            SIZE: 100
          NETWORK_ADDRESS: ${NET_ADDR}
          NETWORK_MASK: ${NET_MASK}
          GATEWAY: ${NET_GW}
          DNS: ${NET_GW}

frontend:
  vars:
    features:
      prometheus: true
      aiops: true
      provision: true
  hosts:
    f1: { ansible_host: ${ONE_HOST} }

node:
  hosts:
    n1: { ansible_host: ${ONE_HOST} }
endef

define TERRAFORM_VARS =
one_password = "${ONE_PASSWORD}"
ssh_public_key = "${SSH_PUB_KEY}"
oned = "http://${ONE_HOST}:2633/RPC2"
oneflow = "http://${ONE_HOST}:2474"
endef

export ONE_DEPLOY_INVENTORY
export TERRAFORM_VARS
